### ISSUE TITLE
nxtpx4 v2是否有位号图

### ISSUE THREAD

**Issue by p-xiexin** [Peize-Liu/NxtPX4-Hardware#3]
我在微空科技购买了v2版本飞控，好像并没有开源。我在某次飞行中“一飞冲天”，落地后发现飞控24v输入口被烧毁了，我现在想尝试做一些维修，请问有位号图参考吗。

**Comment by Peize-Liu** [comment]
看dual 分支

**Comment by p-xiexin** [comment]
嗯嗯好，问题解决了，那边的二极管被击穿了
